window_title: "My window title"
page_title: "My title"

custom_css_files:
  input_data:
    - custom.css
  process_data:
    - custom.css

custom_js_files:
  input_data:
    - custom.js
  process_data:
    - custom.js

flashed_messages:
  - "add warning message here..."

templates:
  ack: null
  about: "custom_about.html"