window_title: "Materials Cloud Tools: an example app"
page_title: "A simple tool example"

#custom_css_files:
# input_data:
#    - custom.css
#  process_data:
#    - custom.css

#custom_js_files:
#  input_data:
#    - custom.js
#  process_data:
#    - custom.js

about_section_title: "About new tool"


templates:
  how_to_cite: "how_to_cite.html"
  about: "custom_about.html"
  select_content: "visualizer_select_structure.html"

use_upload_structure_block: True

additional_accordion_entries:
  - header: "What is this?"
    template_page: what_is.html
  - header: "Acknowledgements"
    template_page: ack.html
