window_title: "Materials Cloud Tools: an example tool (tools-example)"
page_title: "A simple tool example: tools-example"

about_section_title: "About the tools-example tool"

templates:
  how_to_cite: "how_to_cite.html"
  about: "custom_about.html"
  select_content: "additional_selection.html"
  # upload_structure_additional_content: "upload_structure_additional_content.html" # if the upload structure block is present, you can add additional content right above the 'submit' button, if you want (e.g. a disclaimer, terms of use, ...)

use_upload_structure_block: True

additional_accordion_entries:
  - header: "What is this?"
    template_page: what_is.html
  - header: "Acknowledgements"
    template_page: ack.html
